# Generated by Django 4.1.3 on 2023-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('mob_num', models.IntegerField()),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
